import os 

#limpa o terminal.
# os.system("cls || clear")

# #cabeçalho.
# print ('===== =====')
# print ("   SENAI ")
# print ('===== =====')

# nome = input("Digite seu nome: ")
# idade = int(input("Digite sua idade: "))
# peso = float(input("Digite seu peso: "))

os.system("cls || clear")
print ('===== =====')
print (" SENAI BAHIA  ")
print ('===== =====')
nome = input("Digite seu nome: ")

os.system("cls || clear")
print ('===== =====')
print (" SENAI BAHIA  ")
print ('===== =====')
idade = int(input("Digite sua idade: "))

os.system("cls || clear")
print ('===== =====')
print (" SENAI BAHIA  ")
print ('===== =====')
peso = float(input("Digite seu peso: "))





