import os 

#limpa o terminal.
# os.system("cls || clear")

# #cabeçalho.
#funçao
# def logo_senai():

#     os.system("cls || clear")
#     print ('===== =====')
#     print (" SENAI BAHIA  ")
#     print ('===== =====')


# #chamar a funçao
# logo_senai()
# nome = input("Digite seu nome: ")
# logo_senai()
# idade = int(input("Digite sua idade: "))
# logo_senai()
# peso = float(input("Digite seu peso: "))

#limpa o terminal
#cabeçalho
#funçao
#sem retorno
#sem parametros
def logo_senai():

    os.system("cls || clear")
    print ('===== =====')
    print (" SENAI BAHIA  ")
    print ('===== =====')


#chamar a funçao
logo_senai()
nome = input("Digite seu nome: ")
logo_senai()
idade = int(input("Digite sua idade: "))
logo_senai()
peso = float(input("Digite seu peso: "))




