import os 

os.system ('cls || clear')

vetor_notas = []
quantidade_notas = 4

print (f'adicionando {quantidade_notas} notas.')
for i in range(quantidade_notas):
 nota = float(input(f"digite a {i+1}ª nota:"))
 #adicionar nota no vetor
vetor_notas.append(nota)

media = sum  (vetor_notas) / 2


n1 = float(input("digite a primeira nota:"))
n2 = float(input("digite a segunda nota:"))
n3 = float(input("digite sua terceira nota:"))
n4 = float(input("digite sua quarta nbota:"))


if media >
